version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gql_dev
      TZ: 'Asia/Tokyo'
      POSTGRES_INIT_DB_ARGS: '--encoding=UTF-8 --locale=C'
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
